language: python
python:
  - "2.7"
env:
  - DJANGO=1.5 DB=postgres
before_script:
  - psql -c 'create database test_portalturismo;' -U postgres
install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g less
  - pip install -r project/requirements.txt --use-mirrors
script:
  - git submodule init
  - git submodule update
  - mkdir media
  - python manage.py syncdb --settings=project.test_settings --noinput
  - python manage.py migrate_business --settings=project.test_settings
  - coverage run --source=../apps/evento --omit='../apps/*migrations*' test.sh
  - coverage report -m
notifications:
  email:
    recipients:
      - guilherme.vierno@intip.com.br
